- name: Ensure legacy workspace directory
  file:
    path: '{{ ansible_user_dir }}/workspace'
    state: directory

- name: Run FusionComputeCI tests
  shell: |
    cd /opt/stack/nova
    sudo pip install -r test-requirements.txt
    sudo tox -e pep8
  args:
    chdir: "{{ zuul_work_dir }}"
    executable: /bin/bash
